import type { TournamentDataTypes } from "@/types";

export const tournamentData = [
	{
		name: "1. Blitz Open Göppingen 2026",
		status: "completed",
		value: "tournament_1",
		date: "Freitag, 29. Mai 2026",
		startTime: "19:00 Uhr - Meldeschluss bis spätestens 18:30 Uhr",
		endTime: "ca. 00:00 Uhr",
		type: "blitz",
		mode: "13 Runden Schweizer-System - Bedenkzeit: 3 Minuten + 2 Sekunden pro Zug je Spieler und Partie",
		pointRule: "3-point",
		evaluation: "FIDE Blitz Elo",
		entryFee: {
			preRegistration: "15",
			normalRegistration: "20",
		},
		venue: "Ev. Waldheim am Oberholz, Bartenhöhe 43, 73035 Göppingen",
		announcementPath: "/masters/Ausschreibung_Turnier-1_SVA-Masters.pdf",
		listOfAttendeesUrl: null,
		generalInformation:
			"Dieses Turnier wird vom Schachverein Göppingen ausgetragen und ist Teil der SVA Masters Serie.",
	},
	{
		name: "3. Rapid Chess Championship Göppingen 2026",
		status: "completed",
		value: "tournament_2",
		date: "Samstag, 30. Mai 2026",
		startTime: "10:00 Uhr - Meldeschluss bis spätestens 09:30 Uhr",
		endTime: "ca. 18:00 Uhr",
		type: "rapid",
		mode: "9 Runden Schweizer-System - Bedenkzeit: 12 Minuten + 3 Sekunden pro Zug je Spieler und Partie",
		pointRule: "3-point",
		evaluation: "FIDE Rapid Elo",
		entryFee: {
			preRegistration: "25",
			normalRegistration: "30",
		},
		venue: "Ev. Waldheim am Oberholz, Bartenhöhe 43, 73035 Göppingen",
		announcementPath: "/masters/Ausschreibung_Turnier-2_SVA-Masters.pdf",
		listOfAttendeesUrl: null,
		generalInformation:
			"Dieses Turnier wird vom Schachverein Göppingen ausgetragen und ist Teil der SVA Masters Serie.",
	},
	{
		name: "SVA Masters Turnier 3",
		status: "upcoming",
		value: "tournament_3",
		date: "Freitag, 10. Juli 2026",
		startTime: "20:15 Uhr - Meldeschluss bis spätestens 20:00 Uhr",
		endTime: "ca. 23:45 Uhr",
		type: "blitz",
		mode: "13 Runden Schweizer System - Bedenkzeit: 3 Minuten + 2 Sekunden pro Zug je Spieler und Partie",
		pointRule: "3-point",
		evaluation: "FIDE Blitz Elo",
		entryFee: {
			preRegistration: "15",
			normalRegistration: "20",
		},
		venue: "Foyer der Sporthalle, Esslinger Straße 90, 73776 Altbach",
		announcementPath: null,
		listOfAttendeesUrl: null,
		generalInformation: "Wir bieten Pizza und Getränke an.",
	},
	{
		name: "26. Plochinger Marquardt-Schnellschachturnier 2026",
		status: "upcoming",
		value: "tournament_4",
		date: "Samstag, 19.09.2026",
		startTime: null,
		endTime: null,
		type: "rapid",
		mode: null,
		pointRule: "1-point",
		evaluation: "FIDE Blitz Elo",
		entryFee: null,
		venue: null,
		announcementPath: null,
		listOfAttendeesUrl: null,
		generalInformation:
			"Dieses Turnier wird vom Schachverein Plochingen ausgetragen und ist Teil der SVA Masters Serie.",
	},
	{
		name: "SVA Masters Turnier 5",
		status: "upcoming",
		value: "tournament_5",
		date: "Oktober/November",
		startTime: null,
		endTime: null,
		type: "960",
		mode: null,
		pointRule: "3-point",
		evaluation: "FIDE Blitz Elo",
		entryFee: null,
		venue: null,
		announcementPath: null,
		listOfAttendeesUrl: null,
		generalInformation: "Wir bieten Pizza und Getränke an.",
	},
	{
		name: "SVA Masters Finale",
		status: "upcoming",
		value: "tournament_final",
		date: null,
		startTime: null,
		endTime: null,
		type: "final",
		mode: null,
		pointRule: null,
		evaluation: null,
		entryFee: null,
		venue: null,
		announcementPath: null,
		listOfAttendeesUrl: null,
		generalInformation: null,
	},
] satisfies TournamentDataTypes[];
