/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as DatenschutzRouteImport } from "./routes/datenschutz";
import { Route as ImpressumRouteImport } from "./routes/impressum";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as MannschaftenRouteImport } from "./routes/mannschaften";
import { Route as SiegerRouteImport } from "./routes/sieger";

const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);
const DatenschutzRoute = DatenschutzRouteImport.update({
	id: "/datenschutz",
	path: "/datenschutz",
	getParentRoute: () => rootRouteImport,
} as any);
const ImpressumRoute = ImpressumRouteImport.update({
	id: "/impressum",
	path: "/impressum",
	getParentRoute: () => rootRouteImport,
} as any);
const MannschaftenRoute = MannschaftenRouteImport.update({
	id: "/mannschaften",
	path: "/mannschaften",
	getParentRoute: () => rootRouteImport,
} as any);
const SiegerRoute = SiegerRouteImport.update({
	id: "/sieger",
	path: "/sieger",
	getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/datenschutz": typeof DatenschutzRoute;
	"/impressum": typeof ImpressumRoute;
	"/mannschaften": typeof MannschaftenRoute;
	"/sieger": typeof SiegerRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/datenschutz": typeof DatenschutzRoute;
	"/impressum": typeof ImpressumRoute;
	"/mannschaften": typeof MannschaftenRoute;
	"/sieger": typeof SiegerRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/datenschutz": typeof DatenschutzRoute;
	"/impressum": typeof ImpressumRoute;
	"/mannschaften": typeof MannschaftenRoute;
	"/sieger": typeof SiegerRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/datenschutz" | "/impressum" | "/mannschaften" | "/sieger";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/datenschutz" | "/impressum" | "/mannschaften" | "/sieger";
	id:
		| "__root__"
		| "/"
		| "/datenschutz"
		| "/impressum"
		| "/mannschaften"
		| "/sieger";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	DatenschutzRoute: typeof DatenschutzRoute;
	ImpressumRoute: typeof ImpressumRoute;
	MannschaftenRoute: typeof MannschaftenRoute;
	SiegerRoute: typeof SiegerRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/datenschutz": {
			id: "/datenschutz";
			path: "/datenschutz";
			fullPath: "/datenschutz";
			preLoaderRoute: typeof DatenschutzRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/impressum": {
			id: "/impressum";
			path: "/impressum";
			fullPath: "/impressum";
			preLoaderRoute: typeof ImpressumRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/mannschaften": {
			id: "/mannschaften";
			path: "/mannschaften";
			fullPath: "/mannschaften";
			preLoaderRoute: typeof MannschaftenRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/sieger": {
			id: "/sieger";
			path: "/sieger";
			fullPath: "/sieger";
			preLoaderRoute: typeof SiegerRouteImport;
			parentRoute: typeof rootRouteImport;
		};
	}
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	DatenschutzRoute: DatenschutzRoute,
	ImpressumRoute: ImpressumRoute,
	MannschaftenRoute: MannschaftenRoute,
	SiegerRoute: SiegerRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";
import type { getRouter } from "./router.tsx";

declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
